title: 개발도 요리처럼! 망고땡
subtitle: since2020.08.25
author: 망고땡
avatar: /log.png
email: kfc_coco@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: qwe23kr
  card: summary
logo: log.png
social:
  name: kfc_coco
  links:
    - https://github.com/qwe23kr
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
